name: 'streamx-connector-github'
inputs:
  github-token:
    description: 'GitHub token - remove when public access granted'
    required: true
  streamx-ingestion-url:
    description: 'StreamX ingestion api endpoint URL (e.g., https://ingestion.streamx.dev).'
    required: true
  streamx-ingestion-token:
    description: 'StreamX ingestion api authorisation token.'
    required: false
  action:
    description: 'Name of the GH action (e.g., sync, publish, unpublish).'
    required: true
  channel:
    description: 'Name of the StreamX ingestion channel.'
    required: true
  source-provider:
    description: 'Specifies the provider name used to determine the ingestion data source.'
    required: false
  workspace:
    description: 'Specifies the root directory for ingestion data lookup. Defaults to github.workspace.'
    required: false
  type:
    description: 'Specifies the sx:type metadata field within the ingestion message properties.'
    required: false
  include-patterns:
    description: 'Defines Ant-style path patterns for filtering ingestion data (e.g., styles/*.css, scripts/*.js).'
    required: false
  debug-enabled:
    description: 'Configuration property to enable debug log level in GitHub Actions.'
    required: false
    default: 'false'


runs:
  using: "composite"
  steps:
    - name: Inject streamx-connector-github repository credentials
      shell: bash
      run: |
        if [ -f ~/.m2/settings.xml ]; then
          if ! grep -q '<id>streamx-connector-github</id>' ~/.m2/settings.xml; then
            sed -i.bak 's@</servers>@<server><id>streamx-connector-github</id><username>${env.GITHUB_ACTOR}</username><password>${env.GITHUB_TOKEN}</password></server></servers>@' ~/.m2/settings.xml
          fi
        else
          mkdir -p ~/.m2/
          cat <<\EOF > ~/.m2/settings.xml
        <?xml version="1.0"?>
        <settings>
          <servers>
            <server>
              <id>streamx-connector-github</id>
              <username>${env.GITHUB_ACTOR}</username>
              <password>${env.GITHUB_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOF
        fi

    - name: Set up JBang
      uses: jbangdev/setup-jbang@main

    - name: Run the action
      id: action
      run: |
        if [[ "${{ inputs.debug-enabled }}" == "true" ]]; then
          echo $'Inputs:\n{{ toJSON(inputs) }}'
          echo $'Event Inputs:\n{{ toJSON(github.event.inputs) }}'
          export JDK_JAVA_OPTIONS="-Dquarkus.log.category.\"dev.streamx\".level=DEBUG"
        fi
        jbang --java 21 --fresh --repos 'streamx-connector-github=https://maven.pkg.github.com/rafal-glowacz-ds/streamx-connector-github/' --repos 'mavencentral' dev.streamx.githhub:streamx-connector-github:0.0.1-SNAPSHOT
      shell: bash
      env:
        JSON_INPUTS: ${{ toJSON(inputs) }}
        GITHUB_ACTOR: 'rafal-glowacz-ds'
        GITHUB_TOKEN: ${{ inputs.github-token }}
